name: quiet
description: a music player

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: any
  dio: 4.0.0
  dio_cookie_manager: 2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  video_player: ^2.1.10
  url_launcher: ^6.0.9
  intl: ^0.17.0
  sembast: ^3.1.0+2
  scoped_model: ^2.0.0-nullsafety.0
  loader:
    path: loader
  encrypt: ^5.0.0
  netease_music_api:
    path: netease_music_api
  overlay_support: ^1.2.1
  music_player:
    path: music_player
  provider: ^5.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  hive: ^2.0.4
  hooks_riverpod: ^1.0.0-dev.6
  flutter_json_view: ^0.2.1
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  mockito: ^5.0.11
  lint: ^1.5.3
  json_serializable: any

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
